-- DO NOT EDIT THIS FILE. IT IS MANAGED BY THE SHELL AND FOLLOWS STRICT RULES
-- In other words, I ain't writing a lua parser for this, so please be a good boi/girl/whatever
hl.config({ general = { border_size = 1 } })
hl.config({ general = { gaps_in = 2 } })
hl.config({ general = { border_size = 1 } })
hl.config({ input = { touchpad = { natural_scroll = true } } })
hl.config({ input = { touchpad = { disable_while_typing = true } } })
hl.config({ input = { touchpad = { clickfinger_behavior = false } } })
hl.config({ input = { touchpad = { scroll_factor = 0.5 } } })
